### ISSUE TITLE
panic: Error 1040: Too many connections

### ISSUE THREAD

**Issue by philippelecoq** [ansible-semaphore/semaphore#132]
```
panic: Error 1040: Too many connections

goroutine 1406 [running]:
panic(0xa5e780, 0xc820429ec0)
 /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/ansible-semaphore/semaphore/routes/tasks.(*task).log.func1(0xc8202ee2c0, 0xc8204100f0, 0x4e, 0xecef61c8e, 0x1a83d7aa, 0x102bd60)
 /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/tasks/logging.go:36 +0x26c
created by github.com/ansible-semaphore/semaphore/routes/tasks.(*task).log
 /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/tasks/logging.go:38 +0x640
2016/06/17 18:30:06 notifying bugsnag: Error 1040: Too many connections
2016/06/17 18:30:06 bugsnag.Notify: not notifying in development
```

**Comment by matejkramny** [comment]
Hmm i see. The log function for a running task causes a lot of db connections to be opened up.

**Comment by pianzide1117** [comment]
Typically , it happend when run template in debug mode.

**Comment by gcavalcante8808** [comment]
For now an MySQL proxy can handle and close uneeded connections ...

**Comment by lhorace** [comment]
Sorry to bother but the problem still exists with 2.2? Are there two branches? Additionally, MySQL proxy is a workaround? Can someone pitch an example? Additionally, I use Semaphore internally, perhaps I can increase the amount connections, it's not often my MySQL is accepting connections, if not at all, what would be considered a reasonable number?

**Comment by matejkramny** [comment]
It might be simply in mysql client settings to not open so many connections

**Comment by jrm** [comment]
As far as I can see, limiting the number of open connections (SetMaxOpenConns(n)) does not resolve this, I've tested with 100, 200, 1000, 2000.

Its seems the issue is the query rate caused by writing a row per log message line, especially with debug logs, this can be 1000's of lines per second.

I have experimented with a Prepare, Exec, with a defer Close in the log function 'api/tasks/logging.go' which does appear to do better job of reusing connections:

```go
	go func() {
		stmt, err := database.Mysql.Prepare("insert into task__output set task_id=?, task='', output=?, time=?")
		if err != nil {
		    panic(err)
		}
		defer stmt.Close()
		_,err = stmt.Exec(t.task.ID, msg, now)
		if err != nil {
		     panic(err)
		}
	}()
```

**Comment by lhorace** [comment]
Write it to a file?

**Comment by lhorace** [comment]
I am think, how to be _simple_, it just would be easier to write to a file and allow the OS and FS handle cache. Now as far as size, make it turntable ?

**Comment by JanSchr** [comment]
Is there any way to workaround this? I'm having this error now to, with very basic playbooks that just run a simple apt-get dist-upgrade on servers. When there are many updates to install i'm getting this error too. My impression is it happens when the playbook outputs to much info.

From the log:


 201  16:21:39    7.692488ms |   POST    /api/project/1/templates
 200  16:21:39    5.284322ms |   GET     /api/project/1/templates
&{{24 10 waiting false false   0xc4201da000 {63628554105 126919151 0xe76d80} <nil> <nil>} {0 0 0 0 0 <nil>   <nil> false} {0   <nil> <nil> <nil> false} {0  0  <nil> {0   <nil> <nil> <nil> false} <nil> {0   <nil> <nil> <nil> false}  false} {0  0  0 false {0   <nil> <nil> <nil> false}} {0  0 <nil>  false} [] 1 false}
 201  16:21:45   11.135957ms |   POST    /api/project/1/tasks
[1 2]
 200  16:21:45    6.671224ms |   GET     /api/project/1/tasks/24/output
 200  16:21:45     5.07464ms |   GET     /api/users/1
Failed to insert task output: Error 1040: Too many connections
panic: Error 1040: Too many connections

goroutine 3745 [running]:
github.com/ansible-semaphore/semaphore/api/tasks.(*task).log.func1(0xc420428000, 0xc42090a7e0, 0x8a, 0xed08eafc6, 0x20df88f8, 0xe76d80)
        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:37 +0x267
created by github.com/ansible-semaphore/semaphore/api/tasks.(*task).log
        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:39 +0x612
2017/04/23 16:23:02 notifying bugsnag: Error 1040: Too many connections
2017/04/23 16:23:02 bugsnag.Notify: not notifying in development

The mysql log just reads (multiple lines):

2017-04-23T14:23:02.666521Z 472 [Note] Aborted connection 472 to db: 'semaphore' user: 'root' host: 'localhost' (Got an error reading communication packets)

Doesn't seem to be a limit on the MySQL server side, correct?

Kind regards

jan

**Comment by lhorace** [comment]
So far, I haven't ran into this issue by increasing max_connection. The dozen or so message post I have read thus far suggest that 500 seems to be the magic number from the default 200.

**Comment by JanSchr** [comment]
Hi,

in ubuntu LTS 16.04 the default is even lower (just 100). I increased it for now to a 1000 connections and see how it works.

thank you and kind regards

jan

**Comment by JanSchr** [comment]
Even this is not sufficient when running a playbook against 20 servers, went up to 2.500, let's see how it works out.

**Comment by matejkramny** [comment]
note: https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns

**Comment by JanSchr** [comment]
Just for the records: Got it fixed now, it turned out the value configured in my my.cnv actually never really worked because open_files in the os needed to be raised first (due to this it was stuck at 214). Fixed this and now i'm fine (500 seems to work but for safety reasons i'm using 1000 now).

**Comment by strangeman** [comment]
I still have this error on massive Ansible log outputs :(

```
май 24 12:39:07 dev5 semaphore[26609]: time="2018-05-24T12:39:07+03:00" level=panic msg="Error 1040: Too many connections" error="Failed to insert task output"
май 24 12:39:07 dev5 semaphore[26609]: panic: (*logrus.Entry) (0x9eefc0,0xc420a90910)
май 24 12:39:07 dev5 semaphore[26609]: goroutine 92969 [running]:
май 24 12:39:07 dev5 semaphore[26609]: github.com/ansible-semaphore/semaphore/vendor/github.com/Sirupsen/logrus.Entry.log(0xc42009c550, 0xc4213d8c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
май 24 12:39:07 dev5 systemd[1]: semaphore.service: main process exited, code=exited, status=2/INVALIDARGUMENT
май 24 12:39:07 dev5 systemd[1]: Unit semaphore.service entered failed state.
май 24 12:39:07 dev5 systemd[1]: semaphore.service failed.
```

I think we need to implement deferred write to the database.

**Comment by twhiston** [comment]
I would really like to abstract all the database logic away from the controllers and do some work on making this better. I've been messing around with some ideas for this over the last couple of weeks and i'll put together a proposal for it as soon as I have a clear plan.

**Comment by manoj-aps** [comment]
is there any progress on this issue... I'm using Ansible-Semaphore 2.5.1(latest release) and still getting issue on Massive playbook log output.

tried increasing mysql_connections but it seems that hack doesn't work when I'm dealing with unpredictable large output...
