### ISSUE TITLE
Docker Image CrashLoop since v2.9.21 value of field 'Port' is not valid! (Must match regex: '^:([0-9]{1,5})$')

### ISSUE THREAD

**Issue by SwitzerChees** [ansible-semaphore/semaphore#1501]
I noticed that since the version v2.9.21 that was released a few days ago there is a problem with the validation of the postgres port in the connection string. 

When I jump back to the docker image v2.9.19 everything works fine again.

I've tested from version v2.9.21 - v2.8.34 all have the same problem.

Now the question is, is this an expected behaviour since this version or is this just a bug?

Here is the full container log:

```
Attempting to connect to database semaphore on postgresql.postgresql.svc.cluster.local:5432 with user postgres ...
Loading config
Validating config
panic: value of field 'Port' is not valid! (Must match regex: '^:([0-9]{1,5})$')

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/util.validateConfig(...)
	/go/src/github.com/ansible-semaphore/semaphore/util/config.go:397
github.com/ansible-semaphore/semaphore/util.ConfigInit({0x7ffc0163aaa1, 0x1a})
	/go/src/github.com/ansible-semaphore/semaphore/util/config.go:197 +0x24b
github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0xbf2252, 0x4})
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:92 +0x3b
github.com/ansible-semaphore/semaphore/cli/cmd.runService()
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:43 +0x48
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func4(0x273a1a0?, {0xbf2056?, 0x2?, 0x2?})
```

**Comment by fiftin** [comment]
@SwitzerChees it was fixed in v2.9.23.
Could you please check?

**Comment by fiftin** [comment]
Hi @SwitzerChees 
It was fixed in v2.9.23.

In your error message I see old Regexp `^:([0-9]{1,5})$`. It was changed to `^:?([0-9]{1,5})$`.

Are you use Docker or binary?

**Comment by SwitzerChees** [comment]
Hello @fiftin 

Ok I tried it again but this still fails:
<img width="371" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/26026462/2c7fdeb6-48a6-444b-a9c1-d09ecec3ed04">

with these container logs:
<img width="917" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/26026462/95757bb2-fd71-4980-ae9a-4a6c30978952">

I am using the docker image from docker hub but on a Kubernetes cluster. I noticed the issue because I had the :latest tag. Now I switched to a specific version tag and here it works from version v2.9.19 downwards.

**Comment by fiftin** [comment]
Hi @SwitzerChees Thank you! Working on issue

**Comment by fiftin** [comment]
@SwitzerChees Cloud you provide your `port` value?

**Comment by SwitzerChees** [comment]
Yes it's 5432.
It must be surrounded as string for Kubernetes to be a valid deployment manifest:

<img width="358" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/26026462/be60cfe3-bd56-43c4-8064-6858933504dd">

**Comment by fiftin** [comment]
@SwitzerChees The issue with `SEMAPHORE_PORT` not database.

**Comment by SwitzerChees** [comment]
Ok did you changed them in general? Because in the documentation they are named like this:
![image](https://github.com/ansible-semaphore/semaphore/assets/26026462/aa54a0a1-e650-41c5-931b-8ca48cfaac5e)

And when I replace SEMAPHORE_DB_PORT with SEMAPHORE_PORT I get:
<img width="828" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/26026462/fb474c46-26e4-41a6-940a-24fdaffa380c">

**Comment by fiftin** [comment]
No, no :)
It is different variables. `SEMAPHORE_DB_PORT` is required for database.

`SEMAPHORE_PORT` used to change Semaphore listening port.

Do you have `SEMAPHORE_PORT` in your environment variables?

**Comment by SwitzerChees** [comment]
Ok I understand :-).

No I don't set the `SEMAPHORE_PORT` environment variable.

**Comment by fiftin** [comment]
@SwitzerChees another question :)

Do you store `config.json` in volume or mapped directory?

I can't reproduce your issue...

Need more details to fix it.

**Comment by SwitzerChees** [comment]
I have the `config.json` in a mapped ConfigMap in Kubernetes because I had to customize some values in the config that are not possible yet with ENV variables like telegram notifier configurations.

The config looks like this for postgres:
<img width="504" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/26026462/8ed83566-7034-4ca0-b260-8930b26e26ba">

**Comment by vasyan1992** [comment]
Have same issue in k8s 
version: 2.9.37

```
{
 	"mysql": {
 		"host": "mysql:3306",
 		"user": "**********",
 		"pass": "**********",
 		"name": "semaphore",
 		"options": null
 	},
 	"bolt": {
 		"host": "",
 		"user": "",
 		"pass": "",
 		"name": "",
 		"options": null
 	},
 	"postgres": {
 		"host": "",
 		"user": "",
 		"pass": "",
 		"name": "",
 		"options": null
 	},
 	"dialect": "mysql",
 	"port": ":3000",
```

Error: 

```
Loading config
Validating config
panic: value of field 'Port' is not valid: tcp://10.55.255.83:3000 (Must match regex: '^:?([0-9]{1,5})$')

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/util.validateConfig(...)
	/go/src/github.com/ansible-semaphore/semaphore/util/config.go:433
github.com/ansible-semaphore/semaphore/util.ConfigInit({0x7ffeacfbdbd1, 0x21})
	/go/src/github.com/ansible-semaphore/semaphore/util/config.go:204 +0x24b
github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0xbf708e, 0x4})
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:99 +0x3b
github.com/ansible-semaphore/semaphore/cli/cmd.runService()
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:44 +0x48
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func4(0x274f180?, {0xbf6e8e?, 0x2?, 0x2?})
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:18 +0x17
github.com/spf13/cobra.(*Command).execute(0x274f180, {0xc0000d0960, 0x2, 0x2})
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x274db00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:37 +0x5b
main.main()
	/go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17
	```

**Comment by vasyan1992** [comment]
> Have same issue in k8s version: 2.9.37
> 
> ```
> {
>  	"mysql": {
>  		"host": "mysql:3306",
>  		"user": "**********",
>  		"pass": "**********",
>  		"name": "semaphore",
>  		"options": null
>  	},
>  	"bolt": {
>  		"host": "",
>  		"user": "",
>  		"pass": "",
>  		"name": "",
>  		"options": null
>  	},
>  	"postgres": {
>  		"host": "",
>  		"user": "",
>  		"pass": "",
>  		"name": "",
>  		"options": null
>  	},
>  	"dialect": "mysql",
>  	"port": ":3000",
> ```
> 
> Error:
> 
> ```
> Loading config
> Validating config
> panic: value of field 'Port' is not valid: tcp://10.55.255.83:3000 (Must match regex: '^:?([0-9]{1,5})$')
> 
> goroutine 1 [running]:
> github.com/ansible-semaphore/semaphore/util.validateConfig(...)
> 	/go/src/github.com/ansible-semaphore/semaphore/util/config.go:433
> github.com/ansible-semaphore/semaphore/util.ConfigInit({0x7ffeacfbdbd1, 0x21})
> 	/go/src/github.com/ansible-semaphore/semaphore/util/config.go:204 +0x24b
> github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0xbf708e, 0x4})
> 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:99 +0x3b
> github.com/ansible-semaphore/semaphore/cli/cmd.runService()
> 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:44 +0x48
> github.com/ansible-semaphore/semaphore/cli/cmd.glob..func4(0x274f180?, {0xbf6e8e?, 0x2?, 0x2?})
> 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:18 +0x17
> github.com/spf13/cobra.(*Command).execute(0x274f180, {0xc0000d0960, 0x2, 0x2})
> 	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
> github.com/spf13/cobra.(*Command).ExecuteC(0x274db00)
> 	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
> github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
> 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:37 +0x5b
> main.main()
> 	/go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17
> 	```
> ```

@fiftin is issue clear or need additional details?

**Comment by PeterFalken** [comment]
Hi @fiftin,
I stumbled upon this issue and was able to implement a workaround based on your comments.
I'm running the docker image on Kubernetes with a `config.json` file to set the configuration parameters, the `port:` value is empty in order to use the default value.
```
  },
  "dialect": "postgres",
  "port": "",
  "interface": "",
```
It seems that value is not set when using the `config.json` file, this might have been introduced with the refactor of the configuration system. If I add `SEMAPHORE_PORT` with value `":3000"` to the environment variables, the container image starts and works as expected.

I hope this additional information helps. In the meantime it should provide a workaround to anybody else that comes across this issue. Looking forward to the definite fix.

**Comment by ChristianCiach** [comment]
You are all victims of the automatically generated environment variables by the Kubelet. See https://kubernetes.io/docs/tutorials/services/connect-applications-service/#environment-variables

So if you name your Service `semaphore`, Kubernetes will automatically add the env-var `SEMAPHORE_PORT` to the Pods, which of course clashes with Semaphore's own environment variables: https://github.com/ansible-semaphore/semaphore/blob/v2.9.45/util/config.go#L118

Proper fix: If you run Kubernetes with an integrated DNS server (like 99% of people do), you can disable the auto-generated service links. Just add this to your podSpec:

```yaml
    spec:
      enableServiceLinks: false
```

See https://kubernetes.io/docs/tutorials/services/connect-applications-service/#accessing-the-service

> Note: If the service environment variables are not desired (because possible clashing with expected program ones, too many variables to process, only using DNS, etc) you can disable this mode by setting the enableServiceLinks flag to false on the [pod spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#pod-v1-core).

**Comment by PeterFalken** [comment]
Thanks for the insight @ChristianCiach, great catch!!
I can confirm that renaming the service to `semaphoreui`, fixes the issue. 
If the service is renamed, there is no need to change anything on the `pod spec`. The values from the `config.json` are used and defaults are honored.
```
  },
  "dialect": "postgres",
  "port": "",
  "interface": "",
```
@fiftin, I think this solves this particular issue.

**Comment by Dorggie** [comment]
Thanks to @ChristianCiach , it really helps !!
