### ISSUE TITLE
Semaphore can't use ansible.posix.synchronize because rsync is missing in the Docker container

### ISSUE THREAD

**Issue by ziermmar** [ansible-semaphore/semaphore#1564]
Using the provided image: semaphoreui/semaphore, one can't use the module ansible.posix.synchronize out of the box.

ansible.posix.synchronize is just a wrapper around rsync, which is missing in the image

**Comment by ziermmar** [comment]
I just noticed, similar dependency issues are already being discussed and addressed in #1498, however rsync is not a python library dependency

**Comment by Zen3515** [comment]
It would probably be fixed by just adding `rsync` [here](https://github.com/ansible-semaphore/semaphore/blob/c00f5a1ae4cae3f127aca3fd622fbd7f93f61119/deployment/docker/prod/Dockerfile#L13)

```Dockerfile
RUN apk add --no-cache sshpass git curl ansible mysql-client openssh-client-default tini py3-aiohttp && \
    adduser -D -u 1001 -G root semaphore && \
    mkdir -p /tmp/semaphore && \
    mkdir -p /etc/semaphore && \
    mkdir -p /var/lib/semaphore && \
    chown -R semaphore:0 /tmp/semaphore && \
    chown -R semaphore:0 /etc/semaphore && \
    chown -R semaphore:0 /var/lib/semaphore

```

I'll probably open PR myself if it doesn't get fix by the end of this month.

EDIT: Just saw your PR, it's so sad that it doesn't get merged

**Comment by tboerger** [comment]
The rsync package have been already added, this should work with a current version.

**Comment by Apollo3zehn** [comment]
I still get errors like `FAILED! => {"changed": false, "msg": "Failed to find required executable \"rsync\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}` with version `v2.9.64` from hub.docker.com. 

Is it because this line does not contain a reference to `rsync`?
https://github.com/semaphoreui/semaphore/blob/5c507329143d97ba2f139e3d905d2eef78b2913a/deployment/docker/prod/buildx.Dockerfile#L16

**Comment by tboerger** [comment]
Yeah there is a drift between the images, we need to get this straight.

**Comment by airone01** [comment]
Hey. How is this going?

**Comment by tboerger** [comment]
It is part of the `develop` tag now and will be soon part of the next version.
