### ISSUE TITLE
Problem: Boltdb host in config file is not loaded

### ISSUE THREAD

**Issue by Ereaey** [ansible-semaphore/semaphore#2054]
### Issue

Following an upgrade, I no longer have my data.
So I start to check my files and they are there but not read by Sémaphore.
Semaphore actually created a new folder "0.0.0.0" in home without reading the /config which I know is read because it contains the oidc data.
With the environment variable "SEMAPHORE_DB_HOST" I managed to correct my problem.

So I think we should correct the problem first and rename the default value 0.0.0.0 with a new, more relevant name for a quick installation.

### Impact

Database

### Installation method

Docker

### Database

BoltDB

### Browser

Chrome

### Semaphore Version

v2.9.100-beta

### Configuration

Config.json and env variables

**Comment by fiftin** [comment]
Hi @Ereaey thanks a lot for details! I reproduced the issue! Will be fix ASAP.

**Comment by fiftin** [comment]
Hi @Ereaey fixed in v2.9.104-beta.

**Comment by Ereaey** [comment]
@fiftin I still have the problems and now I have the problems, if I set it by the **configuration file (bolt/host)** or the environment variable **(SEMAPHORE_DB_HOST: /home/semaphore/boltdb/database.boltdb)** now the value always remains at "/var/lib/semaphore/database.boltdb"
