### ISSUE TITLE
Problem: send mail don't work and i got errors in app and db log

### ISSUE THREAD

**Issue by EHEX-schildt** [ansible-semaphore/semaphore#3189]
### Issue

Hi,
send mail don't work and i got some error in app and db log if a Run should send a mail in the end.

Versions:
semaphore v2.15.5-2c36360-1754369717
postgres:16

### Impact

Other

### Installation method

Docker

### Database

Postgres

### Browser

Chrome

### Semaphore Version

v2.15.5-2c36360-1754369717

### Ansible Version

```bash

```

### Logs & errors

app log:
```
Pinging database on semaphore-db port 5432...
Generating setup file  ...
Executing semaphore setup

Hello! You will now be guided through a setup to:

1. Set up configuration for a MySQL/MariaDB database
2. Set up a path for your playbooks (auto-created)
3. Run database Migrations
4. Set up initial semaphore user & password

What database to use:
   1 - MySQL
   2 - BoltDB
   3 - PostgreSQL
 (default 1): 
db Hostname (default 127.0.0.1:5432): 
db User (default root): 
db Password: 
db Name (default semaphore): 
Playbook path (default /tmp/semaphore): 
Public URL (optional, example: https://example.com/semaphore): 
Enable email alerts? (yes/no) (default no): 
Enable telegram alerts? (yes/no) (default no): 
Enable slack alerts? (yes/no) (default no): 
Enable Rocket.Chat alerts? (yes/no) (default no): 
Enable Microsoft Team Channel alerts? (yes/no) (default no): 
Enable LDAP authentication? (yes/no) (default no): 
Config output directory (default /home/semaphore): 
Running: mkdir -p /etc/semaphore..
Configuration written to /etc/semaphore/config.json..
Loading config
Validating config
 Pinging db..
Running db Migrations..
Executing migration v0.0.0 (at 2025-08-07 07:19:48.932018873 +0000 UTC)...
Creating migrations table
 [12/0]8]
Executing migration v1.0.0 (at 2025-08-07 07:19:49.068887494 +0000 UTC)...
 [4/87]
Executing migration v1.2.0 (at 2025-08-07 07:19:49.081819086 +0000 UTC)...
 [2/0]6]
Executing migration v1.3.0 (at 2025-08-07 07:19:49.091249713 +0000 UTC)...
 [4/0]]
Executing migration v1.4.0 (at 2025-08-07 07:19:49.097651295 +0000 UTC)...
 [5/0]]]
Executing migration v1.5.0 (at 2025-08-07 07:19:49.111705769 +0000 UTC)...
 [4/0]]]
Executing migration v1.6.0 (at 2025-08-07 07:19:49.13631878 +0000 UTC)...
 [5/0]]
Executing migration v1.7.0 (at 2025-08-07 07:19:49.145054407 +0000 UTC)...
 [2/0]]
Executing migration v1.8.0 (at 2025-08-07 07:19:49.148889491 +0000 UTC)...
 [2/0]]
Executing migration v1.9.0 (at 2025-08-07 07:19:49.153938479 +0000 UTC)...
 [2/0]]
Executing migration v2.2.1 (at 2025-08-07 07:19:49.157751192 +0000 UTC)...
 [5/0]]]
Executing migration v2.3.0 (at 2025-08-07 07:19:49.177593284 +0000 UTC)...
 [4/0]]
Executing migration v2.3.1 (at 2025-08-07 07:19:49.184139227 +0000 UTC)...
 [7/0]]]
Executing migration v2.3.2 (at 2025-08-07 07:19:49.209598223 +0000 UTC)...
 [6/0]]]
Executing migration v2.4.0 (at 2025-08-07 07:19:49.222848707 +0000 UTC)...
 [2/0]]
Executing migration v2.5.0 (at 2025-08-07 07:19:49.227175369 +0000 UTC)...
 [2/0]]
Executing migration v2.5.2 (at 2025-08-07 07:19:49.231496522 +0000 UTC)...
 [2/0]]
Executing migration v2.7.1 (at 2025-08-07 07:19:49.233563521 +0000 UTC)...
 [2/0]]
Executing migration v2.7.4 (at 2025-08-07 07:19:49.237575643 +0000 UTC)...
 [2/0]]
Executing migration v2.7.6 (at 2025-08-07 07:19:49.242043502 +0000 UTC)...
 [2/0]6]
Executing migration v2.7.8 (at 2025-08-07 07:19:49.245489351 +0000 UTC)...
 [4/57]
Executing migration v2.7.9 (at 2025-08-07 07:19:49.251955813 +0000 UTC)...
 [2/77]
Executing migration v2.7.10 (at 2025-08-07 07:19:49.25481609 +0000 UTC)...
 [1/43]
Executing migration v2.7.12 (at 2025-08-07 07:19:49.257488182 +0000 UTC)...
 [3/0]]
Executing migration v2.7.13 (at 2025-08-07 07:19:49.265004563 +0000 UTC)...
 [3/0]2]
Executing migration v2.8.0 (at 2025-08-07 07:19:49.287773599 +0000 UTC)...
 [8/0]]
Executing migration v2.8.1 (at 2025-08-07 07:19:49.309493756 +0000 UTC)...
 [1/63]
Executing migration v2.8.7 (at 2025-08-07 07:19:49.321733148 +0000 UTC)...
 [1/43]
Executing migration v2.8.8 (at 2025-08-07 07:19:49.328171917 +0000 UTC)...
 [2/98]]
Executing migration v2.8.20 (at 2025-08-07 07:19:49.34884044 +0000 UTC)...
 [3/0]9]
Executing migration v2.8.25 (at 2025-08-07 07:19:49.364433107 +0000 UTC)...
 [5/0]]]
Executing migration v2.8.26 (at 2025-08-07 07:19:49.370875994 +0000 UTC)...
 [2/0]]
Executing migration v2.8.36 (at 2025-08-07 07:19:49.374564324 +0000 UTC)...
 [4/0]]
Executing migration v2.8.38 (at 2025-08-07 07:19:49.379744892 +0000 UTC)...
 [9/0]]]
Executing migration v2.8.39 (at 2025-08-07 07:19:49.402675286 +0000 UTC)...
 [8/0]]]
Executing migration v2.8.40 (at 2025-08-07 07:19:49.4167355 +0000 UTC)...
 [7/0]]
Executing migration v2.8.42 (at 2025-08-07 07:19:49.42598346 +0000 UTC)...
 [1/26]
Executing migration v2.8.51 (at 2025-08-07 07:19:49.429910093 +0000 UTC)...
 [3/0]]
Executing migration v2.8.57 (at 2025-08-07 07:19:49.434862821 +0000 UTC)...
 [3/0]]
Executing migration v2.8.58 (at 2025-08-07 07:19:49.439882744 +0000 UTC)...
 [1/57]
Executing migration v2.8.91 (at 2025-08-07 07:19:49.444263792 +0000 UTC)...
 [3/46]
Executing migration v2.9.6 (at 2025-08-07 07:19:49.450342763 +0000 UTC)...
 [1/341]
Executing migration v2.9.46 (at 2025-08-07 07:19:49.468178458 +0000 UTC)...
 [2/0]]
Executing migration v2.9.60 (at 2025-08-07 07:19:49.473747966 +0000 UTC)...
 [5/0]6]
Executing migration v2.9.61 (at 2025-08-07 07:19:49.528227909 +0000 UTC)...
 [9/0]4]
Executing migration v2.9.62 (at 2025-08-07 07:19:49.601893191 +0000 UTC)...
 [5/0]4]
Executing migration v2.9.70 (at 2025-08-07 07:19:49.615094431 +0000 UTC)...
 [3/0]]
Executing migration v2.9.97 (at 2025-08-07 07:19:49.621899762 +0000 UTC)...
 [1/106]
Executing migration v2.9.100 (at 2025-08-07 07:19:49.627006488 +0000 UTC)...
 [1/118]
Executing migration v2.10.12 (at 2025-08-07 07:19:49.632156026 +0000 UTC)...
 [3/75]
Executing migration v2.10.15 (at 2025-08-07 07:19:49.63799525 +0000 UTC)...
 [4/100]
Executing migration v2.10.16 (at 2025-08-07 07:19:49.646579232 +0000 UTC)...
 [3/0]]
Executing migration v2.10.24 (at 2025-08-07 07:19:49.651433607 +0000 UTC)...
 [4/0]]]
Executing migration v2.10.26 (at 2025-08-07 07:19:49.672498229 +0000 UTC)...
 [2/64]
Executing migration v2.10.28 (at 2025-08-07 07:19:49.678722825 +0000 UTC)...
 [3/0]]
Executing migration v2.10.33 (at 2025-08-07 07:19:49.68294022 +0000 UTC)...
 [4/90]
Executing migration v2.10.46 (at 2025-08-07 07:19:49.697997204 +0000 UTC)...
 [2/37]
Executing migration v2.11.5 (at 2025-08-07 07:19:49.70158502 +0000 UTC)...
 [3/69]]
Executing migration v2.12.0 (at 2025-08-07 07:19:49.725024697 +0000 UTC)...
 [3/73]]
Executing migration v2.12.3 (at 2025-08-07 07:19:49.740510123 +0000 UTC)...
 [2/73]
Executing migration v2.12.4 (at 2025-08-07 07:19:49.757254054 +0000 UTC)...
 [1/65]
Executing migration v2.12.5 (at 2025-08-07 07:19:49.770163278 +0000 UTC)...
 [1/48]
Executing migration v2.12.15 (at 2025-08-07 07:19:49.776712689 +0000 UTC)...
 [3/0]]
Executing migration v2.13.0 (at 2025-08-07 07:19:49.78225731 +0000 UTC)...
 [2/66]
Executing migration v2.14.0 (at 2025-08-07 07:19:49.787320341 +0000 UTC)...
 [8/0]]
Executing migration v2.14.1 (at 2025-08-07 07:19:49.799785108 +0000 UTC)...
 [2/134]
Executing migration v2.14.5 (at 2025-08-07 07:19:49.803166043 +0000 UTC)...
 [3/0]]
Executing migration v2.14.7 (at 2025-08-07 07:19:49.806611526 +0000 UTC)...
 [1/28]
Executing migration v2.14.12 (at 2025-08-07 07:19:49.8085301 +0000 UTC)...
 [1/58]
Executing migration v2.15.0 (at 2025-08-07 07:19:49.814066639 +0000 UTC)...
 [3/0]3]
Executing migration v2.15.1 (at 2025-08-07 07:19:49.835386521 +0000 UTC)...
 [1/63]
Migrations Finished


time="2025-08-07T07:19:49Z" level=warning msg="no rows in result set" fields.level=Warn
 > Username:  > Email:  > Your name:  > Password: 
 You are all setup admin!
 Re-launch this program pointing to the configuration file

./semaphore server --config /etc/semaphore/config.json

 To run as daemon:

nohup ./semaphore server --config /etc/semaphore/config.json &

 You can login with operator@my.domain or admin.
No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
Postgres semaphore@semaphore-db:5432 semaphore
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.15.5-2c36360-1754369717
Interface 
Port :3000
Server is running
time="2025-08-07T07:25:43Z" level=info msg="Task 1 added to queue"
time="2025-08-07T07:25:43Z" level=info msg="Set resource locker with TaskRunner 1"
time="2025-08-07T07:25:43Z" level=info msg="Task 1 started"
time="2025-08-07T07:25:43Z" level=error msg="pq: syntax error at or near \"end\""
time="2025-08-07T07:25:49Z" level=info msg="Stopped running TaskRunner 1"
time="2025-08-07T07:25:49Z" level=info msg="Release resource locker with TaskRunner 1"
```

db log:
```
2025-08-07 07:19:44.041 UTC [7] LOG:  database system is ready to accept connections
2025-08-07 07:19:48.931 UTC [62] ERROR:  relation "migrations" does not exist at character 22
2025-08-07 07:19:48.931 UTC [62] STATEMENT:  select count(1) from migrations
2025-08-07 07:19:48.932 UTC [62] ERROR:  relation "migrations" does not exist at character 22
2025-08-07 07:19:48.932 UTC [62] STATEMENT:  select count(1) from migrations
2025-08-07 07:24:44.101 UTC [55] LOG:  checkpoint starting: time
2025-08-07 07:25:16.981 UTC [55] LOG:  checkpoint complete: wrote 330 buffers (2.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=32.836 s, sync=0.035 s, total=32.880 s; sync files=238, longest=0.003 s, average=0.001 s; distance=2045 kB, estimate=2045 kB; lsn=0/1B1DDD0, redo lsn=0/1B1DD60
2025-08-07 07:25:43.753 UTC [63] ERROR:  syntax error at or near "end" at character 42
2025-08-07 07:25:43.753 UTC [63] STATEMENT:  insert into task__stage (task_id, start, end, start_output_id, end_output_id, type) VALUES ($1, $2, $3, $4, $5, $6) returning id
```

### Configuration

app environment:
```
SEMAPHORE_ADMIN_PASSWORD=...
SEMAPHORE_ADMIN_NAME=admin
SEMAPHORE_ADMIN_EMAIL=operator@my.domain
SEMAPHORE_ADMIN=admin
SEMAPHORE_DB_HOST=semaphore-db
SEMAPHORE_DB_PORT=5432
SEMAPHORE_DB_USER=semaphore
SEMAPHORE_DB_PASS=...
SEMAPHORE_DB=semaphore
SEMAPHORE_DB_DIALECT=postgres
SEMAPHORE_ACCESS_KEY_ENCRYPTION=...
SEMAPHORE_WEB_ROOT=https://automate.playground.my.domain
SEMAPHORE_EMAIL_SENDER=automate@my.domain
SEMAPHORE_EMAIL_HOST=smtp.my.domain
SEMAPHORE_EMAIL_PORT=587
SEMAPHORE_EMAIL_USERNAME=noreply@my.domain
SEMAPHORE_EMAIL_PASSWORD=...
SEMAPHORE_EMAIL_SECURE=True
SEMAPHORE_OIDC_PROVIDERS={"idm.my.domain":{"provider_url":"https://idm.my.domain/oauth2/openid/semaphore-playground","client_id":"semaphore-playground","client_secret":"...","redirect_url":"https://automate.playground.my.domain/api/auth/oidc/idm.my.domain/redirect","name_claim":"name","display_name":"Sign in with idm.my.domain"}}
SEMAPHORE_NON_ADMIN_CAN_CREATE_PROJECT=False
```

config.json
```
{
 	"postgres": {
 		"host": "semaphore-db:5432",
 		"user": "semaphore",
 		"pass": "...",
 		"name": "semaphore",
 		"options": {
 			"sslmode": "disable"
 		}
 	},
 	"dialect": "postgres",
 	"tmp_path": "/tmp/semaphore",
 	"web_host": "https://automate.playground.my.domain",
 	"cookie_hash": "...",
 	"cookie_encryption": "...",
 	"access_key_encryption": "..."
 }
```

**Comment by fiftin** [comment]
Fixed here: https://github.com/semaphoreui/semaphore/releases/tag/v2.15.7

**Comment by EHEX-schildt** [comment]
I can confirm that errors in app and db log are gone.

But i still don't get email Alerts on Fails or Success.
