### ISSUE TITLE
Problem: Integrations completely broken after Upgrade to 2.16

### ISSUE THREAD

**Issue by lug-gh** [ansible-semaphore/semaphore#3215]
### Issue

For my automations, I use Semaphore's ‘integrations’, i.e. incoming webhooks, a lot.
Since upgrading to 2.16, these no longer work at all, which is severely limiting my productive operations.
I also noticed in the WebGUI that the integrations there are now somewhat buggy. For example, the matchers are only displayed if you activate the slider for ‘use project alias’ in an integration.

At the same time, I also noticed that the matchers in pre-2.16 were not an AND condition, but an OR condition. Is that correct?

### Impact

Web-Backend (APIs)

### Installation method

Docker

### Database

Postgres

### Browser

Chrome

### Semaphore Version

v2.16.16-4066a1e-1755362172 (PRO)
2.16.10 was the same

### Ansible Version

```bash

```

### Logs & errors
```
semaphore  | time="2025-08-20T13:01:14+02:00" level=info msg="Receiving Integration from: 192.168.X.X"
semaphore  | time="2025-08-20T13:01:14+02:00" level=info msg="1 integrations found for alias 0vqddzdXXXXXXX"
semaphore  | time="2025-08-20T13:01:14+02:00" level=info msg="Running integration 4"
semaphore  | time="2025-08-20T13:01:14+02:00" level=error msg="Failed to get task definition" context=integrations error="unexpected end of JSON input" integration_id=4
```

**Comment by lug-gh** [comment]
I tested further. Newly created integrations are not affected by this. However, I have to activate the ‘Use project alias’ slider to define the matchers, then deactivate it again to be able to use my integration alias. I can no longer see the matchers, but they still work.

However, it seems that the existing matchers cannot be edited either. For example, if I change the comparison method from == to !=, I see the following in the log

```
semaphore  | time="2025-08-20T13:15:51+02:00" level=info msg="Updating API Matcher 21 for Extractor 16, matcher ID: 21"
semaphore  | time="2025-08-20T13:15:51+02:00" level=info msg="Err %!s(<nil>)"
```

In the web interface, the change from equals to unequals is made correctly, but in the backend it remains equals. (Dangerous!)

I also updated to 2.16.17, but unfortunately without any change.

**Comment by holzi1005** [comment]
For me, also new integrations with an JSON Body Value Extraction result in an error.

The ingrations in triggered by forgejo, gitea or github

**Comment by lug-gh** [comment]
@fiftin Thanks for the quick reply. Yes, the tasks are now triggered with the integration, but as @holzi1005 wrote, the values are not extracted for the taks, thus it starts with empty survey variables.
Also, the matcher is still only visibile when enabling the global project alias, configuring it and disabling it again.
And editing an existing matcher still only changes in the Frontend, not in the backend.

**Comment by fiftin** [comment]
Hi @lug-gh got it. Thank you. Will fix ASAP.

**Comment by lug-gh** [comment]
@fiftin it's almost a month now. Is it safe to roll back to 2.15.x?

**Comment by bbaassssiiee** [comment]
With a new integration in SemaphoreUI **2.16.31-d14fa6b-1758101338** 

I see the "Survey Variables" on creation, for instance `my_extra_var` (great!).
I created an Extracted Value for the playbook's extra_vars.

<img width="800" height="955" alt="Image" src="https://github.com/user-attachments/assets/9958e217-deed-4fff-843f-d1cf2d2af219" />

Now I simply trigger the integration with:

```sh 
curl --v -u ****:**** -X POST -H 'Content-Type: application/json' -d '{ "my_extra_var": "42" }' https://semaphoreui.example.com/api/integrations/***
```

But I notice a `502: Bad Gateway response` where Nginx logs:
```
upstream prematurely closed connection while reading response header from upstream
```

Such an integration did start under Semaphore 2.15, but the data was not passed. [#3240](https://github.com/semaphoreui/semaphore/issues/3240) 

It was suggested to upgrade to 2.16, now I'm stuck.

**Comment by lug-gh** [comment]
@fiftin What do you mean by ‘ASAP’? As a Pro customer, I am very disappointed to constantly see updates with new features or colour changes to buttons instead of fixes for bugs in existing features that make them completely unusable.

**Comment by fiftin** [comment]
@lug-gh I'm really sorry for this. Fixed in 2.16.37

**Comment by lug-gh** [comment]
@fiftin nope, still not working with 2.16.37

Existing Integrations still don't extract anything.

A newly created integration appears to attempt to extract something, but the value in the task is <nil> when I set the variable type to environment. With variable type ‘Task’, semaphore throws a panic message.
time="2025-10-30T12:51:21+01:00" level=info msg="Running integration 17"
2025/10/30 12:51:21 http: panic serving 100.64.1.4:37762: assignment to entry in nil map
goroutine 7800 [running]:

I don't have permission to reopen the issue.

**Comment by alexhellmann** [comment]
I have the same issue.

**Comment by ddejan75** [comment]
In my case there is no error, but there is no extracted value at all:
```
time="2025-10-31T22:54:22+01:00" level=info msg="Receiving Integration from: 10.0.0.2"
time="2025-10-31T22:54:22+01:00" level=info msg="1 integrations found for alias wnunu6zislxprgp2"
time="2025-10-31T22:54:22+01:00" level=info msg="Running integration 2"
time="2025-10-31T22:54:22+01:00" level=info msg="Task 2147483168 added to queue"
time="2025-10-31T22:54:22+01:00" level=info msg="Set resource locker with TaskRunner 2147483168"
time="2025-10-31T22:54:22+01:00" level=info msg="Task 2147483168 started"
```
and the ansible output on simple debug:
```
10:54:28 PM TASK [debug]  *******************************************************************
10:54:28 PM ok: [my_host] => {
10:54:28 PM       "variable": "VARIABLE IS NOT DEFINED!"
10:54:28 PM }

**Comment by bbaassssiiee** [comment]
Can someone post an isolated test case? Parsing a POST request with a JSON payload, how hard can that be?

**Comment by fiftin** [comment]
Hi @lug-gh , @ddejan75 , @bbaassssiiee I can't reproduce the issue. I need more context.

**Comment by rmtsrc** [comment]
1. Create and Git commit the following debug Ansible file:

`output-var.yaml`
```yaml
---
- name: Example playbook to print a variable
  hosts: "{{ hosts }}"

  vars:
    # Default value if not provided
    my_var: 'my_var was NOT provided'

  tasks:
    - name: Print the variable value
      debug:
        msg: 'The value of my_var is: {{ my_var }}'
```

2. In Semaphore **Task Templates > New Template > Ansbile Playbook** enter a name, path to the yaml file and select your inventory, repo, variables groups. Then in **Survey Variable** add a new **Required** variable `my_var` as a string
3. **Integrations > New Integration** enter a name and select the `output-var` task template, auth method **None**
4. Click the name of the new integration
5. Check **Use project alias**
6. **New matcher** Name: integration, Match on: Body, Format: JSON, Key: integration, Comparison: `==`, Value: output-var
7. **New extracted value** Source: Body, Type: JSON, Key: `hosts`, Usage: Environment, Variable: `hosts`. Do the same for `my_var`

<img width="1000" height="757" alt="Image" src="https://github.com/user-attachments/assets/880cd2dd-a8be-4e02-92df-41d2158e10eb" />

8. Back on **Integrations** tab **Add Alias** (if one doesn't already exist) and copy it
9. Run the following cURL changing the URL to match the Alias URL: `curl --request POST --url https://semaphore.example.com/api/integrations/YoUr_KeY --header 'content-type: application/json' --data '{ "integration": "output-var", "hosts": "localhost", "my_var": "string from a cURL request" }'`

Check the Dashboard for the expected successful output (`v2.15.7`):

```
PLAY [Example playbook to print a variable] ************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Print the variable value] ************************************************
ok: [localhost] => 
  msg: 'The value of my_var is: string from a cURL request'

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

On `v2.16` and higher the task fails with missing hosts and `my_var`

**Comment by lug-gh** [comment]
What @rmtsrc  wrote, plus newly created integrations behave very differently in the error pattern created before 2.16. It would be nice not to have to recreate every single integration and roll it out again at all external points.

In my case, the variable to be extracted is ‘vm_name’. In an integration created before 2.16, this is what it looks like in the task when you press the restart button:

<img width="497" height="675" alt="Image" src="https://github.com/user-attachments/assets/e2c5f2b8-aa6c-41ff-bc14-9372e64886ba" />

And in a newly created integration (settings 1:1 identical), it looks like this:

<img width="503" height="676" alt="Image" src="https://github.com/user-attachments/assets/c330ac8c-49d1-4ab6-903a-32378b3a2421" />

In addition, the matchers still disappear as soon as you deactivate the ‘use project alias’ slider, but as I said, they only seem to be hidden until you reactivate the slider.

**Comment by fiftin** [comment]
Hi @rmtsrc reproduced. Fixed.
Hi @lug-gh reproduced. Fixed.

v2.16.43

**Comment by lug-gh** [comment]
**Edit:** nevermind. it works now.  curl commands in terraform have to be escaped, now i changed it to your example and it works.

@rmtsrc @alexhellmann Does the fix work for you? It still doesn't work for me. “<nil>” no longer appears in the task, but the variable is completely empty. In Ansible, I get the error message “The task includes an option with an undefined variable... ‘vm_name’ is undefined.”
It doesn't matter whether I select variables or task params in the integration under “variable usage,” neither works.

`curl -X POST -H 'Content-Type: application/json' -d '{\"vm_name\": \"tf-proxmox-upgrade-test-1\", \"triggered_by\": \"proxmox_create_vm\"}' https://semaphore.example.org/api/integrations/21cn5qm17t9l5mmc`

<img width="1104" height="574" alt="Image" src="https://github.com/user-attachments/assets/0b44ecae-d07c-4004-afd0-15f5971201bf" />

**Comment by alexhellmann** [comment]
@lug-gh yes the fix work for me. My Playbook runs with the correct values:

<img width="1367" height="497" alt="Image" src="https://github.com/user-attachments/assets/1d6bf330-a9c5-4877-8954-c7db65146a11" />

Edit: Ah I did not see your edit :)
