### ISSUE TITLE
Text in Template Description Field not Saved rel_2.7.12

### ISSUE THREAD

**Issue by scomcd** [ansible-semaphore/semaphore#717]
Running ansible-semaphore 2.7.12 (upgraded from 2.7.0 on OS, Oracle Linux 8.x)
In the new Description field for the Task Templates, we have tried adding text then clicking 'save' but when we re-open
 the Template for editing, the description text we added is missing.

**Comment by fiftin** [comment]
Hi @scomcd ,

I can't reproduce the bug. Please try v2.7.14

Fixed in v2.7.14

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.14

**Comment by scomcd** [comment]
Hi @fiftin
I have upgraded our Semaphore system to v2.7.14 but unfortunately for us the problem remains.
The only way I can add text to the description field is directly via a mysql statement in the Database, 
then it is displayed in the browser.

If I enable the general log for MariaDB, I can see where the insert occurrs, but it appears to be missing data for 
the 'description' field.


                    10 Query    insert into event(user_id, project_id, object_id, object_type, description, created) values (10, 2, 4, 'template', 'Template ID 4 updated', '2021-09-09 00:50:59.549942')

**Comment by fiftin** [comment]
Hi @scomcd ,

Fixed in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.15

**Comment by scomcd** [comment]
Hi @fiftin,

Thanks very much for the quick response. Confirming the issue is fixed in v2.7.15
